name: build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: SerVB/setup-python@customPythonVersion
        with:
          python-version: "2.7.7"
          architecture: "x86"
      - name: Clone repo
        uses: actions/checkout@master
      - name: Build recent-stat
        run: python build.py
